# Generated by Django 5.2.2 on 2025-06-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="video_game_name",
            field=models.CharField(
                db_column="VideoGameName", max_length=255, unique=True
            ),
        ),
    ]
