# Generated by Django 5.2.2 on 2025-06-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_id",
            field=models.AutoField(
                db_column="answer_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="database.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.CharField(db_column="difficulty", max_length=6),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_id",
            field=models.AutoField(
                db_column="question_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                db_column="quiz_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="database.quiz",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_id",
            field=models.AutoField(
                db_column="quiz_id", primary_key=True, serialize=False
            ),
        ),
    ]
