# Generated by Django 5.2.2 on 2025-06-24 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="database.question",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                db_column="quiz_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="database.quiz",
            ),
        ),
        migrations.CreateModel(
            name="AnonAnsweredQuestion",
            fields=[
                (
                    "user_answered_question_id",
                    models.AutoField(
                        db_column="user_answered_question_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField(db_column="session_id")),
                (
                    "answer",
                    models.ForeignKey(
                        db_column="answer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        db_column="quiz_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "AnonAnsweredQuestion",
            },
        ),
    ]
