# Generated by Django 5.2.2 on 2025-07-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="box_art",
            field=models.ImageField(
                db_column="box_art", null=True, upload_to="box_art"
            ),
        ),
    ]
